services:
  - type: web
    name: arxiv-star-viewer
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: STAR_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: BASE_URL
        value: "https://arxiv.org/list/cs.AI/recent"
      - key: GOOGLE_MODEL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11